name: Publish to GCR

on:
  push:
    branch: ['master']
  pull_request:
    branch: ['master']

jobs:
  push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower-case image name
        run: |
          echo "IMAGE_LC=${IMAGE,,}" >> ${GITHUB_ENV}
        env:
          IMAGE: '${{ github.repository }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context:  .
          push: true
          tags: ghcr.io/${{ IMAGE_LC }}:latest
